CREATE TABLE users (
    id UUID NOT NULL UNIQUE PRIMARY KEY,
    email VARCHAR(255) UNIQUE,
    password VARCHAR(72) NOT NULL,
    phone_number VARCHAR(255) UNIQUE,
    profile_image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);