spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  autoconfigure:
    exclude: com.google.cloud.spring.autoconfigure.core.GcpContextAutoConfiguration,com.google.cloud.spring.autoconfigure.storage.GcpStorageAutoConfiguration
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
jwt:
  accessKey: ${JWT_ACCESS_KEY}
  refreshKey: ${JWT_REFRESH_KEY}
  exp: ${JWT_EXP}
#gcp:
#  bucketName: ${GCP_BUCKET_NAME}
#utils:
#  defaultImagePath: ${DEFAULT_IMAGE_PATH}
