apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-postgres-deployment
spec:
  selector:
    matchLabels:
      app: identity-postgres
  template:
    metadata:
      labels:
        app: identity-postgres
    spec:
      containers:
        - name: identity-postgres
          image: postgres:alpine
          ports:
            - containerPort: 5432
              name: tcp-connection
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: dbuser
                  name: identity-postgres-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: dbpassword
                  name: identity-postgres-secret
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: dbname
                  name: identity-postgres-secret
