apiVersion: v1
kind: Secret
metadata:
  name: identity-container-secret
data:
  dbuser: dXNlcg==
  dbpassword: MTIzNDU2Nzg=
  dbname: aWRlbnRpdHk=
  accesskey: MTIzNDU2Nzg5MTIzNDU2Nzg5MTIzNDU2Nzg5MTIzNDU2Nzg5
  refreshkey: YWJjZGVmZ2hpamFiY2RlZmdoaWphYmNkZWZnaGlqYWJjZGVmZ2hpamFiY2RlZmdoaWo=
  kid: QWExN3RHN0lkalpfb2UyeFk3MTNnZ1VTUm8zOUM5T2dqbTRiNEk3bk5RUQo=
---
apiVersion: v1
kind: Secret
metadata:
  name: identity-postgres-secret
data:
  dbuser: dXNlcg==
  dbpassword: MTIzNDU2Nzg=
  dbname: aWRlbnRpdHk=
